application: szkocka-1080
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app

libraries:
- name: MySQLdb
  version: latest
- name: pycrypto
  version: latest