application: szkocka-1080
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /tasks/.*
  script: main.app
  login: admin
- url: .*
  script: main.app

env_variables:
    IMAGES_BUCKET: 'szkocka-1080-images'
    DEFAULT_IMAGE: 'http://storage.googleapis.com/szkocka-1080-images/default.gif'
    TOKEN_SEED: 'aqswdefrgthyujikolzsxxdcfvgbhnjmk'
    SENDER_EMAIL: 'admin@szkocka-1080.appspotmail.com'